name: angular_name
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  common_name:
    path: ../common_name
  angular: ^7.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  flutter_lints: ^2.0.0