name: common_name
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  library_architecture_mvvm_modify: ^0.0.2
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.0